name: Build and push Docker image
on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: app

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{vars.REGISTRY_URL}}
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and load
        uses: docker/build-push-action@v3
        with:
          context: './app/src'
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{secrets.REGISTRY_URL}}/images/testtuesapp:${{github.sha}}
          labels: |
            org.opencontainers.image.description=testtuesapp Docker image

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{secrets.REGISTRY_URL}}/images/testtuesapp:${{github.sha}}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        env:
          TRIVY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
          TRIVY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: './app/src'
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{secrets.REGISTRY_URL}}/images/testtuesapp:latest
          labels: |
            org.opencontainers.image.description=testtuesapp Docker image